server:
  servlet:
    context-path: /api/minesweeper
  port: ${PORT}
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /
    endpoint:
      health:
        show-details: always
spring:
  data:
    mongodb:
      uri: mongodb+srv://application:${DB_PASS}@minescluster.jw2wr.mongodb.net/minesweeper?retryWrites=true&w=majority
